data diabetes;
set diabetes;
if glyhb ge 7 then glyhb_range='Diabetes';
if glyhb lt 7 and glyhb ge 6 then glyhb_range='Prediabetes';
if glyhb lt 6 then glyhb_range='Normal';
WHRatio = waist / hip;
run;
proc glm data=diabetes;
class glyhb_range;
model ratio bp_1s bp_1d age stab_glu WHRatio = glyhb_range;
manova h=_all_ / printe printh;
run;
proc glm data=diabetes;
class glyhb_range;
model ratio bp_1s age stab_glu WHRatio = glyhb_range;
means glyhb_range / Tukey;
run;
proc discrim data=diabetes pooled=no;
class glyhb_range;
var chol stab_glu hdl ratio age height weight bp_1s bp_1d waist hip WHRatio;
run;
